name: Bicep Validation

on:
  pull_request:
    paths:
      - 'bicep/**'
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Bicep Validation
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          deploymentName: validate-${{ github.run_number }}
          template: ./bicep/main.bicep
          parameters: environment=dev
          deploymentMode: Validate
