name: Terraform Deployment

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      working-directory: terraform/environments/${{ github.event.inputs.environment || 'dev' }}
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
          -backend-config="key=${{ github.event.inputs.environment || 'dev' }}.tfstate" \
          -backend-config="resource_group_name=${{ secrets.TF_RESOURCE_GROUP }}" \
          -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"

    - name: Terraform Format
      working-directory: terraform/environments/${{ github.event.inputs.environment || 'dev' }}
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: terraform/environments/${{ github.event.inputs.environment || 'dev' }}
      run: |
        terraform plan \
          -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      working-directory: terraform/environments/${{ github.event.inputs.environment || 'dev' }}
      run: terraform apply -auto-approve tfplan

    - name: Terraform Output
      if: success()
      working-directory: terraform/environments/${{ github.event.inputs.environment || 'dev' }}
      run: |
        echo "Resource Group Details:" >> $GITHUB_STEP_SUMMARY
        terraform output >> $GITHUB_STEP_SUMMARY

  notify:
    needs: terraform
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify Deployment Status
      uses: actions/github-script@v6
      with:
        script: |
          const success = context.job.status === 'success';
          const environment = '${{ github.event.inputs.environment || 'dev' }}';
          const message = `Terraform deployment to ${environment} ${success ? 'succeeded' : 'failed'}`;
          
          if (context.issue.number) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message
            });
          } 